services:
  - type: web
    name: marketing_ai_agent
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python interfaces/server.py"
    plan: free
    envVars:
      - key: OPENAI_API_KEY   # אם עוד לא הגדרת – חובה!
        sync: false